Relikt_2/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Relikt_2_DataAccess;
using Relikt_2_DataAccess.Repository.IRepository;
using Relikt_2_Models;
using Relikt_2_Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Relikt_2.Controllers
{
    [Authorize(Roles = WC.AdminRole)]
    public class CategoryController : Controller
    {
        private readonly ICategoryRepository _catRepo;
        public CategoryController(ICategoryRepository catRepo)
        {
            _catRepo = catRepo;
        }
        public IActionResult Index()
        {
            IEnumerable<Category> objList = _catRepo.GetAll();
            return View(objList);
        }


        //GET - CREATE
        public IActionResult Create()
        {
            
            return View();
        }

        //POST - CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category obj)
        {
            if(ModelState.IsValid)
            {
                _catRepo.Add(obj);
                _catRepo.Save();
                TempData[WC.Success] = "Категория удачно создана";
                return RedirectToAction("Index");
            }
            TempData[WC.Error] = "ОШИБКА во время создания категории";
            return View(obj);
        }

        //GET - EDIT
        public IActionResult Edit(int? id)
        {
            if(id==null||id==0)
            {
                return NotFound();
            }

            var obj = _catRepo.Find(id.GetValueOrDefault());
            if(obj==null)
            {
                return NotFound();
            }
            return View(obj);
        }

        //POST - EDIT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category obj)
        {
            if (ModelState.IsValid)
            {
                _catRepo.Update(obj);
                _catRepo.Save();
                TempData[WC.Success] = "Действие выполнено успешно";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //GET - DELETE
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var obj = _catRepo.Find(id.GetValueOrDefault());
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        //POST - DELETE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _catRepo.Find(id.GetValueOrDefault());
            if (obj == null)
            {
                return NotFound();
            }
            TempData[WC.Success] = "Действие выполнено успешно";
            _catRepo.Remove(obj);
            _catRepo.Save();
                return RedirectToAction("Index");
            
            
        }
    }
}

Relikt_2/Views/Category/Create.cshtml
@model Relikt_2_Models.Category

<form method="post" asp-action="Create">
    <div class="border p-3 bg-white">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-info pl-3">Добавить Категорию</h2>
        </div>

        <div class="row">
            <div class="col-8">
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="DisplayOrder"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="DisplayOrder" class="form-control" />
                        <span asp-validation-for="DisplayOrder" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Создать" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"><i class="fas fa-sign-out-alt"></i>
                                Вернуться
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>
</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

Relikt_2/Views/Category/Delete.cshtml
@model Relikt_2_Models.Category

<form method="post" asp-action="DeletePost">
    <input asp-for="Id" hidden />
    <div class="border p-3 bg-white">
        
        <div class="form-group row">
            <h2 class="text-info pl-3">Удалить Категорию</h2>
        </div>

        <div class="row">
            <div class="col-8">
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" disabled class="form-control" />
                        
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="DisplayOrder"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="DisplayOrder" disabled class="form-control" />
                        
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-danger w-100" value="Удалить" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"><i class="fas fa-sign-out-alt"></i>
                                Вернуться
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>
</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

Relikt_2/Views/Category/Edit.cshtml
@model Relikt_2_Models.Category

<form method="post">
    <input asp-for="Id" hidden />
    <div class="border p-3 bg-white">
        
        <div class="form-group row">
            <h2 class="text-info pl-3">Редактировать Категорию</h2>
        </div>

        <div class="row">
            <div class="col-8">
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="DisplayOrder"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="DisplayOrder" class="form-control" />
                        <span asp-validation-for="DisplayOrder" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Обновить" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"><i class="fas fa-sign-out-alt"></i>
                                Вернуться
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>
</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

Relikt_2/Views/Category/Index.cshtml
@model IEnumerable<Relikt_2_Models.Category>

<div class="container p-3 bg-white">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Список Категорий</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="Category" asp-action="Create" class="btn btn-primary">
                <i class="fas fa-plus"></i> &nbsp; Создать Новую Категорию
            </a>
        </div>
    </div>

    <br /><br />

    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Название Категории
                    </th>
                    <th>
                        Порядок Отображения
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                    <tr>
                        <td width="50%">@obj.Name</td>
                        <td width="30%">@obj.DisplayOrder</td>
                        <td class="text-center">
                            <div class="w-100 btn-group" role="group">
                                <a asp-controller="Category" asp-route-Id="@obj.Id" asp-action="Edit" class="btn btn-primary mx-2">
                                    <i class="fas fa-edit"></i> 
                                </a>
                                <a asp-controller="Category" asp-route-Id="@obj.Id" asp-action="Delete" class="btn btn-danger mx-2">
                                    <i class="far fa-trash-alt"></i> 
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>Категории не существуют...</p>
    }
</div>