Relikt_2/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Relikt_2_DataAccess;
using Relikt_2_DataAccess.Repository.IRepository;
using Relikt_2_Models;
using Relikt_2_Models.ViewModels;
using Relikt_2_Utility;
using Relikt_2_Utility.BrainTree;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;

namespace Relikt_2.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IEmailSender _emailSender;
        private readonly IApplicationUserRepository _userRepo;
        private readonly ICategoryRepository _catRepo;
        private readonly IApplicationTypeRepository _appTypeRepo;
        private readonly ISizeTypeRepository _sizeTypeRepo;
        private readonly IRightLeftRepository _rightLeftRepo;
        private readonly IColourOfGlassRepository _colourOfGlassRepo;
        private readonly IProductRepository _prodRepo;
        private readonly IInquiryHeaderRepository _inqHRepo;
        private readonly IInquiryDetailRepository _inqDRepo;
        private readonly IOrderHeaderRepository _orderHRepo;
        private readonly IOrderDetailRepository _orderDRepo;
        private readonly ICouponRepository _coupRepo;
        private readonly IExcelDownload _exelDow;
        //private readonly IBrainTreeGate _brain;

        [BindProperty]
        public ProductUserVM ProductUserVM { get; set; }
        public CartController(IWebHostEnvironment webHostEnvironment, IEmailSender emailSender,
            IApplicationUserRepository userRepo, ICategoryRepository catRepo, IApplicationTypeRepository appTypeRepo,
            ISizeTypeRepository sizeTypeRepo, IRightLeftRepository rightLeftRepo,
            IColourOfGlassRepository colourOfGlassRepo, IProductRepository prodRepo,
            IInquiryHeaderRepository inqHRepo, IInquiryDetailRepository inqDRepo,
            IOrderHeaderRepository orderHRepo, IOrderDetailRepository orderDRepo,
            ICouponRepository coupRepo, IExcelDownload exelDow
            //IBrainTreeGate brain
            )
        {

            _webHostEnvironment = webHostEnvironment;
            _emailSender = emailSender;
            _userRepo = userRepo;
            _catRepo = catRepo;
            _appTypeRepo = appTypeRepo;
            _sizeTypeRepo = sizeTypeRepo;
            _rightLeftRepo = rightLeftRepo;
            _colourOfGlassRepo = colourOfGlassRepo;
            _prodRepo = prodRepo;
            _inqDRepo = inqDRepo;
            _inqHRepo = inqHRepo;
            _orderDRepo = orderDRepo;
            _orderHRepo = orderHRepo;
            _coupRepo = coupRepo;
            _exelDow = exelDow;
            //_brain = brain;
        }
        public IActionResult Index(Coupon coupon = null)
        {
            List<ShoppingCart> shoppingCartList = new List<ShoppingCart>();
            if (HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WC.SessionCart) != null
                && HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WC.SessionCart).Count() > 0)
            {
                // Сессия существует
                shoppingCartList = HttpContext.Session.Get<List<ShoppingCart>>(WC.SessionCart);
            }

            List<int> prodInCart = shoppingCartList.Select(i => i.ProductId).ToList();
            //IEnumerable<Product> prodList = _prodRepo.GetAll(u => prodInCart.Contains(u.Id), includeProperties: "Category,ApplicationType,SizeType");
            IEnumerable<Product> prodListTemp = _prodRepo.GetAll(u => prodInCart.Contains(u.Id), includeProperties: "Category,ApplicationType,SizeType,RightLeft,ColourOfGlass");
            IList<Product> prodList = new List<Product>();

            foreach (var cartObj in shoppingCartList)
            {
                Product prodTemp = prodListTemp.FirstOrDefault(u => u.Id == cartObj.ProductId);
                prodTemp.TempCount = cartObj.CountFt;
                prodList.Add(prodTemp);
            }
            var cartVM = new CartVM { Products = prodList.ToList(), Coupon = coupon };
            return View(cartVM); //тут другая модель будет
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Index")]
        public IActionResult IndexPost(IEnumerable<Product> Products)
        {
            List<ShoppingCart> shoppingCartList = new List<ShoppingCart>();
            foreach (Product prod in Products)
            {
                shoppingCartList.Add(new ShoppingCart { ProductId = prod.Id, CountFt = prod.TempCount });
            }
            HttpContext.Session.Set(WC.SessionCart, shoppingCartList);

            return RedirectToAction(nameof(Summary));
        }


        public IActionResult Summary()
        {
            ApplicationUser applicationUser;
            var orderNumber = 0;
            if (User.IsInRole(WC.AdminRole))
            {
                if (HttpContext.Session.Get<int>(WC.SessionInquiryId) != 0)
                {
                    //cart has been loaded using an inquiry
                    InquiryHeader inquiryHeader = _inqHRepo.FirstOrDefault(u => u.Id == HttpContext.Session.Get<int>(WC.SessionInquiryId));
                    applicationUser = new ApplicationUser()
                    {
                        Email = inquiryHeader.Email,
                        FullName = inquiryHeader.FullName,
                        PhoneNumber = inquiryHeader.PhoneNumber
                    };
                }
                else
                {
                    applicationUser = new ApplicationUser();
                    orderNumber = (_orderHRepo.GetAll().LastOrDefault()?.Id ?? 0) + 1;
                }
                //var claimsIdentity = (ClaimsIdentity)User.Identity;
                //var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

                //var gateway = _brain.GetGateway();
                //var clientToken = gateway.ClientToken.Generate(
                //    new ClientTokenRequest
                //    {
                //        CustomerId = claim.Value
                //    }
                //);
                //ViewBag.ClientToken = clientToken;
                //var gateway = _brain.GetGateway();
                //var clientToken = gateway.ClientToken.Generate();
                //ViewBag.ClientToken = clientToken;
            }
            else
            {
                var claimsIdentity = (ClaimsIdentity)User.Identity;
                var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
                //var userId = User.FindFirstValue(ClaimTypes.Name);

                applicationUser = _userRepo.FirstOrDefault(u => u.Id == claim.Value);
            }

            List<ShoppingCart> shoppingCartList = new List<ShoppingCart>();
            if (HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WC.SessionCart) != null
                && HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WC.SessionCart).Count() > 0)
            {
                // Сессия существует
                shoppingCartList = HttpContext.Session.Get<List<ShoppingCart>>(WC.SessionCart);
            }

            List<int> prodInCart = shoppingCartList.Select(i => i.ProductId).ToList();
            IEnumerable<Product> prodList = _prodRepo.GetAll(u => prodInCart.Contains(u.Id), includeProperties: "Category,ApplicationType,SizeType,RightLeft,ColourOfGlass");
            var couponFromDb = _coupRepo.FirstOrDefault(c => !string.IsNullOrEmpty(HttpContext.Session.GetString(WC.ssCouponCode)) ? c.Name.ToLower() == HttpContext.Session.GetString(WC.ssCouponCode).ToLower() : false);
            ProductUserVM = new ProductUserVM()
            {
                ApplicationUser = applicationUser,
                Coupon = couponFromDb
                //ProductList = prodList.ToList()
            };
            foreach (var cartObj in shoppingCartList)
            {
                Product prodTemp = _prodRepo.FirstOrDefault(u => u.Id == cartObj.ProductId);
                prodTemp.TempCount = cartObj.CountFt;
                ProductUserVM.ProductList.Add(prodTemp);
            }
            ProductUserVM.OrderHeader = new OrderHeader { Id = orderNumber };

            return View(ProductUserVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Summary")]
        public async Task<IActionResult> SummaryPost(IFormCollection collection, ProductUserVM ProductUserVM)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (User.IsInRole(WC.AdminRole))
            {
                //нужно создать заказ
                //var orderTotal = 0.0;
                //foreach (Product prod in ProductUserVM.ProductList)
                //{
                //    orderTotal += prod.Price * prod.TempCount;
                //}
                OrderHeader orderHeader = new OrderHeader()
                {
                    CreatedByUserId = claim.Value,
                    FinalOrderTotal = ProductUserVM.ProductList.Sum(x => x.TempCount * x.Price),
                    City = ProductUserVM.ApplicationUser.City,
                    StreetAddress = ProductUserVM.ApplicationUser.StreetAddress,
                    Region = ProductUserVM.ApplicationUser.Region,
                    PostalCode = ProductUserVM.ApplicationUser.PostalCode,
                    FullName = ProductUserVM.ApplicationUser.FullName,
                    Email = ProductUserVM.ApplicationUser.Email,
                    PhoneNumber = ProductUserVM.ApplicationUser.PhoneNumber,
                    OrderDate = DateTime.Now,

Relikt_2/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Relikt_2_DataAccess.Repository.IRepository;
using Relikt_2_Models.ViewModels;
using Relikt_2_Utility;
using Relikt_2_Utility.BrainTree;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Text;
using Relikt_2_Models;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;

namespace Relikt_2.Controllers
{
    [Authorize(Roles = WC.AdminRole)]
    public class OrderController : Controller
    {
        private readonly ICategoryRepository _catRepo;
        private readonly IApplicationTypeRepository _appTypeRepo;
        private readonly ISizeTypeRepository _sizeTypeRepo;
        private readonly IRightLeftRepository _rightLeftRepo;
        private readonly IColourOfGlassRepository _colourOfGlassRepo;
        private readonly IProductRepository _prodRepo;
        private readonly IOrderHeaderRepository _orderHRepo;
        private readonly IOrderDetailRepository _orderDRepo;
        private readonly ICouponRepository _coupRepo;
        //private readonly IBrainTreeGate _brain;

        [BindProperty]
        public OrderVM OrderVM { get; set; }
        public OrderController(ICategoryRepository catRepo, IApplicationTypeRepository appTypeRepo,
            ISizeTypeRepository sizeTypeRepo, IRightLeftRepository rightLeftRepo,
            IColourOfGlassRepository colourOfGlassRepo, IProductRepository prodRepo,
            IOrderHeaderRepository orderHRepo, IOrderDetailRepository orderDRepo,
            ICouponRepository coupRepo
            //IBrainTreeGate brain
            )
        {
            _catRepo = catRepo;
            _appTypeRepo = appTypeRepo;
            _sizeTypeRepo = sizeTypeRepo;
            _rightLeftRepo = rightLeftRepo;
            _colourOfGlassRepo = colourOfGlassRepo;
            _prodRepo = prodRepo;
            _orderDRepo = orderDRepo;
            _orderHRepo = orderHRepo;
            _coupRepo = coupRepo;
            //_brain = brain;
        }
        public IActionResult Index(string searchName = null, string searchEmail = null, string searchPhone = null, string Status = null)
        {
            OrderListVM orderListVM = new OrderListVM()
            {
                OrderHList = _orderHRepo.GetAll(),


                StatusList = WC.listStatus.ToList().Select(i => new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem
                {
                    Text = i,
                    Value = i
                })
            };

            if (!string.IsNullOrEmpty(searchName))
            {
                orderListVM.OrderHList = orderListVM.OrderHList.Where(u => u.FullName.ToLower().Contains(searchName.ToLower()));
            }
            if (!string.IsNullOrEmpty(searchEmail))
            {
                orderListVM.OrderHList = orderListVM.OrderHList.Where(u => u.Email.ToLower().Contains(searchEmail.ToLower()));
            }
            if (!string.IsNullOrEmpty(searchPhone))
            {
                orderListVM.OrderHList = orderListVM.OrderHList.Where(u => u.PhoneNumber.ToLower().Contains(searchPhone.ToLower()));
            }
            if (!string.IsNullOrEmpty(Status) && Status != "--Статус Заказа--")
            {
                orderListVM.OrderHList = orderListVM.OrderHList.Where(u => u.OrderStatus.ToLower().Contains(Status.ToLower()));
            }

            return View(orderListVM);
        }

        public IActionResult Details(int id)
        {
            
            OrderVM = new OrderVM()
            {
                
                OrderHeader = _orderHRepo.FirstOrDefault(u => u.Id == id),
                OrderDetail = _orderDRepo.GetAll(o => o.OrderHeaderId == id, includeProperties: "Product,Category,ApplicationType,SizeType,RightLeft,ColourOfGlass"),

                Categories = _catRepo.GetAll(),
                ApplicationTypes = _appTypeRepo.GetAll(),
                SizeTypes = _sizeTypeRepo.GetAll(),
                RightLefts = _rightLeftRepo.GetAll(),
                ColourOfGlasses = _colourOfGlassRepo.GetAll(),
                //Coupon = _coupRepo.GetCoupons(orderID) 
                Coupons=_coupRepo.GetAll()
                
            };
            
            




            return View(OrderVM);
        }
        [HttpPost]
        public IActionResult StartProcessing()
        {
            OrderHeader orderHeader = _orderHRepo.FirstOrDefault(u => u.Id == OrderVM.OrderHeader.Id);
            orderHeader.OrderStatus = WC.StatusInProcess;
            _orderHRepo.Save();
            TempData[WC.Success] = "Заказ В Работе";
            return RedirectToAction(nameof(Index));
        }



        [HttpPost]
        public IActionResult ShipOrder()
        {
            OrderHeader orderHeader = _orderHRepo.FirstOrDefault(u => u.Id == OrderVM.OrderHeader.Id);
            orderHeader.OrderStatus = WC.StatusShipped;
            orderHeader.ShippingDate = DateTime.Now;
            _orderHRepo.Save();
            TempData[WC.Success] = "Готов";
            return RedirectToAction(nameof(Index));
        }
        //[HttpPost]
        //public IActionResult CancelOrder()
        //{
        //    OrderHeader orderHeader = _orderHRepo.FirstOrDefault(u => u.Id == OrderVM.OrderHeader.Id);

        //    var gateway = _brain.GetGateway();
        //    Transaction transaction = gateway.Transaction.Find(orderHeader.TransactionId);

        //    if (transaction.Status == TransactionStatus.AUTHORIZED || transaction.Status == TransactionStatus.SUBMITTED_FOR_SETTLEMENT)
        //    {
        //        //no refund
        //        Result<Transaction> resultvoid = gateway.Transaction.Void(orderHeader.TransactionId);
        //    }
        //    else
        //    {
        //        //refund
        //        Result<Transaction> resultRefund = gateway.Transaction.Refund(orderHeader.TransactionId);
        //    }
        //    orderHeader.OrderStatus = WC.StatusRefunded;
        //    _orderHRepo.Save();
        //    TempData[WC.Success] = "Заказ Закрыт Успешно";
        //    return RedirectToAction(nameof(Index));
        //}

        [HttpPost]
        public IActionResult UpdateOrderDetails()
        {
            OrderHeader orderHeaderFromDb = _orderHRepo.FirstOrDefault(u => u.Id == OrderVM.OrderHeader.Id);
            orderHeaderFromDb.FullName = OrderVM.OrderHeader.FullName;
            orderHeaderFromDb.PhoneNumber = OrderVM.OrderHeader.PhoneNumber;
            orderHeaderFromDb.StreetAddress = OrderVM.OrderHeader.StreetAddress;
            orderHeaderFromDb.City = OrderVM.OrderHeader.City;
            orderHeaderFromDb.Region = OrderVM.OrderHeader.Region;
            orderHeaderFromDb.PostalCode = OrderVM.OrderHeader.PostalCode;
            orderHeaderFromDb.Email = OrderVM.OrderHeader.Email;
            orderHeaderFromDb.Comments = OrderVM.OrderHeader.Comments;

            _orderHRepo.Save();
            TempData[WC.Success] = "Детали заказа успешно обновлены";

            return RedirectToAction("Details", "Order", new { id = orderHeaderFromDb.Id });
        }



    }
}

Relikt_2/Views/Order/Details.cshtml
@model Relikt_2_Models.ViewModels.OrderVM
@using Relikt_2_Utility

<form method="post">
    <input asp-for="OrderHeader.Id" hidden />
    <br />
    <div class="backgroundWhite container">
        <div class="card">
            <div class="card-header bg-dark text-light ml-0 row container">
                <div class="col-12 d-none d-md-block col-md-6 pb-1">
                    <i class="fas fa-shopping-cart"></i> &nbsp; Детали Заказа

                </div>

                <div class="col-12 col-md-4 offset-md-2 text-right">
                    <a asp-controller="Order" asp-action="Index" class="btn btn-outline-info form-control btn-sm">Возврат к Заказам</a>

                </div>
            </div>
            <div class="card-body pb-0">
                <div class="container rounded p-2">
                    <div class="row">
                        <div class="col-12 col-lg-6 pb-4">
                            <div class="row">
                                <h4 class="d-flex justify-content-between align-items-center mb-3">
                                    <span class="text-info">Детали Заказа:</span>

                                </h4>
                            </div>
                            <div class="row my-1">
                                <div class="col-3">Имя</div>
                                <div class="col-9">

                                    <input asp-for="OrderHeader.FullName" type="text" class="form-control" />
                                    <span asp-validation-for="OrderHeader.FullName" class="text-danger"></span>


                                </div>
                            </div>
                            <div class="row my-1">
                                <div class="col-3">Телефон</div>
                                <div class="col-9">

                                    <input asp-for="OrderHeader.PhoneNumber" type="text" class="form-control" />
                                    <span asp-validation-for="OrderHeader.PhoneNumber" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="row my-1">
                                <div class="col-3">Улица</div>
                                <div class="col-9">

                                    <input asp-for="OrderHeader.StreetAddress" type="text" class="form-control" />
                                    <span asp-validation-for="OrderHeader.StreetAddress" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="row my-1">
                                <div class="col-3">Город</div>
                                <div class="col-9">

                                    <input asp-for="OrderHeader.City" type="text" class="form-control" />
                                    <span asp-validation-for="OrderHeader.City" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="row my-1">
                                <div class="col-3">Область</div>
                                <div class="col-9">

                                    <input asp-for="OrderHeader.Region" type="text" class="form-control" />
                                    <span asp-validation-for="OrderHeader.Region" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="row my-1">
                                <div class="col-3">Номер дома, Новой Почты</div>
                                <div class="col-9">

                                    <input asp-for="OrderHeader.PostalCode" type="text" class="form-control" />
                                    <span asp-validation-for="OrderHeader.PostalCode" class="text-danger"></span>

                                </div>
                            </div>
                            <div class="row my-1">
                                <div class="col-3">Email</div>
                                <div class="col-9">

                                    <input asp-for="OrderHeader.Email" type="text" class="form-control" />
                                    <span asp-validation-for="OrderHeader.Email" class="text-danger"></span>

                                </div>
                            </div>
                            <div class="row my-1">
                                <div class="col-3">Дата Заказа</div>
                                <div class="col-9">

                                    <input value="@Model.OrderHeader.OrderDate.ToShortDateString()" type="text" class="form-control" readonly />

                                </div>
                            </div>

                            <div class="row my-1">
                                <div class="col-3">Дата отгрузки</div>
                                <div class="col-9">
                                    <input value="@Model.OrderHeader.ShippingDate.ToLongDateString()" id="shippingDate" type="text" readonly class="form-control" />
                                </div>
                            </div>

                            <div class="row my-1">
                                <div class="col-3">ID Транзакции</div>
                                <div class="col-9">
                                    <input asp-for="OrderHeader.TransactionId" type="text" readonly class="form-control" />
                                </div>
                            </div>
                            <div class="row my-1">
                                <div class="col-3">Статус Заказа</div>
                                <div class="col-9">
                                    <input asp-for="OrderHeader.OrderStatus" type="text" readonly class="form-control" />
                                </div>
                            </div>
                            <div class="row my-1">
                                <div class="col-3">Дополнительные инструкции</div>
                                <div class="col-9">

                                    @*<input asp-for="OrderHeader.Comments" type="text" class="form-control" />*@
                                    <textarea asp-for="OrderHeader.Comments" style="height:100px;" class="form-control"></textarea>
                                    <span asp-validation-for="OrderHeader.Comments" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="row my-1">
                                <div class="col-9 offset-3">
                                    <input type="submit" value="Обновить детали заказа" class="btn btn-warning form-control"
                                           asp-action="UpdateOrderDetails" formmethod="post" />
                                </div>
                            </div>


                        </div>
                        <div class="col-12 col-lg-5 offset-lg-1">
                            <h4 class="d-flex justify-content-between align-items-center mb-3">
                                <span class="text-info">Итог заказа</span>

                            </h4>
                            @*<a asp-action="ExcelDownload"
        class="btn btn-success">Сохранить заказ как Exel файл</a>*@
                            @*<a href="/Relikt_2_Utility/ExcelDownload">Сохранить заказ как Exel файл</a>*@
                            @*<input type="submit" value="Сохранить заказ как Exel файл" class="btn btn-info" />*@
                            <ul class="list-group mb-3">
                                @{ var orderTotal = 0.0;}
                                @foreach (var detail in Model.OrderDetail)
                                {

                                    <li class="list-group-item d-flex justify-content-between p-2">
                                        <div class="row container">
                                            <div class="col-8">
                                                <h6 class="my-0 text-info">@detail.Product.Name</h6>
                                                @if (detail.Product.ApplicationType != null)
                                                {
                                                    <h6 class="my-0 text-info">@detail.Product.ApplicationType.Name</h6>
                                                }
                                                @if (detail.Product.Category != null)
                                                {
                                                    <h6 class="my-0 text-info">@detail.Product.Category.Name</h6>
                                                }
                                                @if (detail.Product.SizeType != null)
                                                {
                                                    <h6 class="my-0 text-info">@detail.Product.SizeType.Name</h6>
                                                }

                                                @if (detail.Product.ColourOfGlass != null)
                                                {
                                                    <h6 class="my-0 text-info">@detail.Product.ColourOfGlass?.Name</h6>
                                                }
                                                @if (detail.Product.RightLeft != null)
                                                {
                                                    <h6 class="my-0 text-info">@detail.Product.RightLeft?.Name</h6>
                                                }

                                                <small class="text-muted">Цена : @detail.PriceCount</small><br />
                                                <small class="text-muted">Количество : @detail.UnitCount</small>
                                            </div>
                                            <div class="col-4">
                                                <p class="text-success">@(detail.PriceCount * detail.UnitCount) грн.</p>
                                            </div>
                                        </div>
                                    </li>
                                    orderTotal += detail.PriceCount * detail.UnitCount;
                                }

                                @if (Model.Coupons != null)
                                {
                                    <li class="list-group-item d-flex justify-content-between">
                                        <div class="text-success">
                                            <h6 class="my-0">Скидка составила: </h6>

                                        </div>


                                        <span class="text-success">-@(Model.OrderHeader.CouponCodeDiscount) грн.</span>

                                    </li>
                                }
                                <li class="list-group-item bg-info">
                                    <div class="row container">
                                        <div class="col-6">
                                            <h5 class="text-white">ИТОГО </h5>
                                        </div>

                                        <div class="col-6 text-right">
                                            <h5 class="text-white">@(Model.OrderHeader.FinalOrderTotal) грн.</h5>
                                        </div>
                                    </div>
                                </li>

                            </ul>


                            <br />

                            @if (Model.OrderHeader.OrderStatus == Relikt_2_Utility.WC.StatusPending)
                            {
                                <input type="submit" value="Запуск в работу"
                                       formmethod="post" asp-action="StartProcessing"
                                       class="btn btn-info form-control" />
                            }

                            @if (Model.OrderHeader.OrderStatus == Relikt_2_Utility.WC.StatusInProcess)
                            {
                                <input type="submit" value="Готов"
                                       formmethod="post" asp-action="ShipOrder"
                                       class="btn btn-primary form-control" />
                            }
                            @*@if (Model.OrderHeader.OrderStatus != Relikt_2_Utility.WC.StatusRefunded
           && Model.OrderHeader.OrderStatus != Relikt_2_Utility.WC.StatusCancelled)
        {
            <div class="pt-2">
                <button type="submit"
                        class="btn btn-danger form-control"
                        asp-action="CancelOrder"
                        formmethod="post">
                    Заказ закрыт
                </button>
            </div>
        }*@
                            <br />
                            <br />
                            <br />
                            <br />
                            <button asp-controller="Cart" asp-action="ExcelDownload" class="btn btn-success" onclick="return validateInput()" id="submit-button">Сохранить заказ как Exel файл</button>
                        </div>
                        
                    </div>
                    
                </div>

            </div>

        </div>

    </div>

</form>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
    <script>
        $(document).ready(function () {
            var shippingDate = document.getElementById("shippingDate");

            if (shippingDate.value == '1 января 0001 г.') {
                shippingDate.value = "";
            }
        })
    </script>

} 